#自定义参数
myprops:
  clientId: CKI4ep3SxiG8HuiYi1CbnbVE
  clientSecret: 2ekjAwcVZougT6zAqdFEpyLBjMyGKXxc
server:
  port: 8102
  #servlet:
   # context-path: /admin_system
spring:

  #profiles: stage
  application:
      name: admin_system
  redis:
      host: 39.99.177.49
      port: 6379
      timeout: 60000
  datasource:
    druid:
      url: jdbc:mysql://39.99.177.49/admin_system?characterEncoding=utf-8
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
#热部署是否启用
  devtools:
    restart:
      enabled: true
#  设置静态资源
  mvc.static-path-pattern: /**
  resources.static-locations: classpath:/static/

#邮箱
  mail:
#    username: liulebinn@163.com
    username: 18340013921@163.com
#    password: llb1998
    password: IATJLZAGAWJMKMCX
    host: smtp.163.com
    default-encoding: utf-8
#    配置邮件服务器的端口，默认25端口，但是阿里云和腾讯云服务器为了安全关闭端口
    port: 465

    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          ssl.enable: true
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          starttls.enable: true
          socketFactory.port: 465　
          port: 465

#    properties:
#      mail:
#        smtp:
#          socketFactory:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory
#            fallback: false
##STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
#        starttls:
#          enable: true
#          required: true
#邮件发件人
mail:
  fromMail:
#    addr: liulebinn@163.com
    addr: 18340013921@163.com

#thymeleaf
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

#mybatis
mybatis-plus:
  type-aliases-package: com.llb.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    驼峰命名
    map-underscore-to-camel-case: true
#    二级缓存
    cache-enabled: false
#    Mapper返回值为HashMap时，数据库空字段依旧返回为null
    call-setters-on-nulls: true

#打印日志
logging:
  level:
    root: info
    org.mybatis: info
    com.llb: debug