server:
  port: 8102
spring:
  application:
      name: admin_system
  datasource:
    druid:
      url: jdbc:mysql://www.liulebin.cn/driver_school?characterEncoding=utf-8
      username: root
      password: nevergiveup?
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
#热部署是否启用
  devtools:
    restart:
      enabled: true
#  设置静态资源
  mvc.static-path-pattern: /**
  resources.static-locations: classpath:/static/

#thymeleaf
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

#mybatis
mybatis-plus:
  type-aliases-package: com.llb.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    驼峰命名
    map-underscore-to-camel-case: true
#    二级缓存
    cache-enabled: false


#打印日志
logging:
  level:
    root: info
    org.mybatis: info
    com.llb: debug